### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cache')

### ISSUE THREAD

**Issue by sonofescobar1337** [osman-koc/openai-discord-bot#1]
TypeError: Cannot read properties of undefined (reading 'cache')
C:\Users\Administrator\openai-discord-bot\node_modules\discord.js\src\client\actions\MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read properties of undefined (reading 'cache')
    at MessageCreateAction.handle (C:\Users\Administrator\openai-discord-bot\node_modules\discord.js\src\client\actions\MessageCreate.js:11:41)
    at module.exports [as MESSAGE_CREATE] (C:\Users\Administrator\openai-discord-bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Administrator\openai-discord-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Administrator\openai-discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Administrator\openai-discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Administrator\openai-discord-bot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (C:\Users\Administrator\openai-discord-bot\node_modules\ws\lib\websocket.js:1068:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (C:\Users\Administrator\openai-discord-bot\node_modules\ws\lib\receiver.js:517:14)

**Comment by Nishant1500** [comment]
If i remember correctly you need `Message Content` Intent enabled for that

> https://discord-api-types.dev/api/discord-api-types-v10/enum/GatewayIntentBits#MessageContent

**Comment by osman-koc** [comment]
Hi @sonofescobar1337 , as far as I've looked I haven't found a problem. Was @Nishant1500 's answer sufficient? Does your problem persist?
